language: objective-c
osx_image: xcode6.4
script:
    - xcodebuild -project TimesSquare.xcodeproj -scheme TimesSquare -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build